#ifndef STATUS_H
#define STATUS_H

enum
{
    STATUS_EXIT_SUCCESS = 0,
    STATUS_EXIT_NO_INPUT_FILE,
    STATUS_EXIT_INVALID_INPUT_FILE,
    STATUS_EXIT_SYNTAX_ERROR,
    STATUS_EXIT_SEMANTIC_ERROR
};

#endif