name: Etapa4
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: etape4
    steps:
    - uses: actions/checkout@v1
    - name: Compilation
      run: make clean || make
    - name: Run tests
      run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    - name: Give permission to run deploy script
      run: chmod +x ./deploy.ci.sh
    - name: Deploy it
      run: ./deploy.ci.sh etapa4 ${{ secrets.SCP_PASSWORD }}